- name: Install ansible prerequisites
  apt:
    name: ["apt-transport-https", "software-properties-common"]
    update_cache: yes
    state: latest

- name: Add ansible PPA repository
  apt_repository:
    repo: "ppa:ansible/ansible"

- name: Install ansible
  apt:
    name: ["ansible"]
    update_cache: yes
