# Update a debian machine
- name: apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install dependancies
  apt:
    name:
      [
        "arping",
        "bridge-utils",
        "cpu-checker",
        "dnsmasq",
        "dnsutils",
        "etcd-client",
        "git",
        "gunicorn3",
        "libssl-dev",
        "libvirt-daemon-system",
        "libvirt-dev",
        "net-tools",
        "prometheus-node-exporter",
        "pwgen",
        "python-libvirt",
        "python3-libvirt",
        "qemu-kvm",
        "unzip",
      ]
    state: latest

- name: Disable dnsmasq
  service:
    name: dnsmasq
    enabled: no
    state: stopped

- name: Configure KSM (kernel same-page merging)
  lineinfile:
    path: /etc/default/qemu-kvm
    regexp: '^KSM_ENABLED='
    line: 'KSM_ENABLED={{ shakenfist_ksm | default("AUTO") }}'
  register: result_ksmconf

- name: Restart KVM service if KSM setting changed
  service:
    name: qemu-kvm
    state: restarted
  when: result_ksmconf.changed
