# Update a debian machine
- name: apt-get dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install dependancies
  apt:
    name: "{{ shakenfist_deps }}"
    state: latest

- name: Disable dnsmasq
  service:
    name: dnsmasq
    enabled: no
    state: stopped

- name: Enable time service
  service:
    name: "{{ shakenfist_service_time | default('chrony') }}"
    enabled: yes
    state: started
